version: '3.6'
services:
  agama:
    image: agama:latest
    restart: always
    build: .
    environment:
      - AGAMA_DATABASE_URI={{ mysql_con }}
    ports:
      - '{{ agama_port }}:8000'
    volumes:
      - /opt/agama:/etc/agama