- name: Install influxd
  apt:
    name: influxdb
    state: present
  register: inluxdb_installed

- name: Install influxdb python module
  pip:
    name: influxdb
    state: present

- name: Wait for port influxd port to start listening
  wait_for:
    port: "{{ influxdb_port }}"
    delay: 5

- name: copy over influxdb conf
  template:
    src: influxdb.conf
    dest: /etc/influxdb/influxdb.conf
  notify: restart influxdb

- name: start enable influxd
  service:
    name: influxdb
    state: started
    enabled: yes