- name: check if agama namespace exists
  shell: "rbd namespace ls | grep agama"
  register: agama_namespace
  changed_when: false
  failed_when: false

- name: create agama namespace
  shell:
    cmd: rbd namespace create --namespace agama
  when: agama_namespace.stdout == ""

- name: check if agama user exists
  stat:
    path: "/etc/ceph/ceph.client.agama.keyring"
  register: agama_keyring
  changed_when: false

- name: create user for agama namespace
  shell:
    cmd: ceph auth get-or-create client.agama mon 'profile rbd' osd 'profile rbd pool=rbd namespace=agama' -o /etc/ceph/ceph.client.agama.keyring
  when: not agama_keyring.stat.exists

- name: check if agama-image exists
  shell: "rbd --namespace agama ls"
  register: agama_image
  changed_when: false

- name: create agama rbd image
  shell:
    cmd: "rbd create --namespace agama agama-image --size {{ agama_image_size }}"
  when: agama_image.stdout == ""

- name: get current agama-image size
  shell: rbd --image agama-image --namespace agama info | grep -oP '\tsize\s+\K(\d+\s+\w)' | sed 's/ //g'
  register: current_agama_image_size
  changed_when: false
  failed_when: false

- name: resize agama-image
  shell:
    cmd: "rbd resize --image agama-image --namespace agama --size {{ agama_image_size }} --allow-shrink"
  when: "current_agama_image_size.stdout != '{{ agama_image_size }}'"
