- name: install apache2 and requirements
  apt:
    name:
      - apache2
      - xorriso
      - isolinux
      - snap

- name: start enable apache2
  service:
    name: apache2
    state: started
    enabled: yes

- name: copy over apache.conf
  template:
    src: apache.conf
    dest: /etc/apache2/apache.conf
  register: apache_conf

- name: copy over 000-default.conf
  template:
    src: 000-default.conf
    dest: /etc/apache2/sites-enabled/000-default.conf
  register: default_conf

- name: restart apache
  systemd:
    name: apache2
    state: restarted
    daemon_reload: yes
  when: default_conf.changed or apache_conf.changed
