authtoken: {{ ngrok_auth_token }}
region: {{ ngrok_region }}
tunnels:
  ssh:
    proto: tcp
    addr: 22
    console_ui: false
  http:
    proto: http
    addr: 80
    hostname: {{ ngrok_hostname }}
    console_ui: false