version: '3.4'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    network_mode: host
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    logging:
      driver: "syslog"
      options:
        tag: "docker/{{'{{.Name}}'}}"
