- name: Update APT cache
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Upgrade apt
  apt:
    upgrade: yes

- name: create vm user
  user:
    name: "{{ inventory_hostname }}"
    shell: /bin/bash
    append: yes

- name: add vm user to sudoers group with nopasswd
  copy:
    dest: "/etc/sudoers.d/{{ inventory_hostname }}"
    content: "{{ inventory_hostname }} ALL=(ALL) NOPASSWD:ALL"