- name: generate rsa ssh key
  openssh_keypair:
    owner: "{{ inventory_hostname }}"
    path: "/home/{{ inventory_hostname }}/.ssh/id_rsa"
    type: rsa
    size: 4096
    state: present
    force: no
  register: id_rsa
  notify:
    - add public keys to user authorized_keys
    - add root public keys to user authorized_keys

- name: generate root rsa ssh key
  openssh_keypair:
    owner: root
    path: "/root/.ssh/id_rsa"
    type: rsa
    size: 4096
    state: present
    force: no
  register: root_id_rsa
  notify:
    - add root public key to root authorized_keys
    - add public key to root authorized_keys

- name: register public key
  set_fact:
    public_key: "{{ id_rsa.public_key }}"
    cacheable: yes

- name: register root public key
  set_fact:
    root_public_key: "{{ root_id_rsa.public_key }}"
    cacheable: yes

- name: add local ssh key to authorized keys
  authorized_key:
    user: "{{ inventory_hostname }}"
    state: present
    key: "{{ item }}"
  loop: "{{ public_keys }}"

- name: add local ssh key to root authorized keys
  authorized_key:
    user: root
    state: present
    key: "{{ item }}"
  loop: "{{ public_keys }}"

- name: overwrite sshd_config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
  notify: restart sshd