- name: Install bind9 and dnspython
  apt:
    name:
      - bind9
      - python3-dnspython

- name: get old domain_name
  shell:
    cmd: "named-checkconf -p | grep zone | cut -d '\"' -f2 | grep -v in-addr | head -1"
  failed_when: false
  changed_when: "old_domain_name.stdout != '{{ domain_name }}'"
  register: old_domain_name
  notify: restart named

- name: delete old masters
  file:
    state: absent
    path: "/var/cache/bind/db.{{ item }}"
  loop:
    - "{{ domain_name }}"
    - "{{ reverse }}"
    - "{{ old_domain_name.stdout }}"
  when: old_domain_name.changed

- name: copy over config
  ansible.builtin.template:
    src: named.conf.options
    dest: /etc/bind/named.conf.options
  notify: restart bind9
  register: config
  no_log: true

- name: master zone config
  template:
    src: named.conf.local
    dest: /etc/bind/named.conf.local
  notify: restart bind9
  when: inventory_hostname in groups['dns_master']

- name: slave zone config
  template:
    src: named.conf.local.slave
    dest: /etc/bind/named.conf.local
  notify: restart bind9
  when: inventory_hostname in groups['dns_slave']

- name: rndc reload
  become: yes
  ansible.builtin.shell:
    cmd: "rndc reload"
  when: config.changed

- name: restart bind9
  ansible.builtin.service:
    name: bind9
    state: restarted
  when: config.changed

- name: Add masters
  ansible.builtin.template:
    src: "{{ item[0] }}"
    dest: "/var/cache/bind/db.{{ item[1] }}"
    force: no
  loop:
    - ["master", "{{ domain_name }}"]
    - ["reverse-master", "{{ reverse }}"]
  notify:
    - rndc reload
    - restart bind9
  when: inventory_hostname in groups['dns_master']
  register: rndc

- name: start enable bind9
  service:
    name: bind9
    state: started
    enabled: yes
