- name: Update APT cache
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Upgrade apt
  apt:
    upgrade: yes

- name: get current hostname
  shell:
    cmd: hostname
  register: hostname
  changed_when: false

- name: set hostname
  shell:
    cmd: "hostnamectl set-hostname srvr-{{ inventory_hostname[-1] }}"
  when: "'srvr-{{ inventory_hostname[-1] }}' != hostname.stdout"

- name: add hostname to /etc/hosts
  become: true
  blockinfile:
    path: /etc/hosts
    block: "127.0.0.1 srvr-{{ inventory_hostname[-1] }}"

- name: add user to sudoers group with nopasswd
  copy:
    dest: "/etc/sudoers.d/{{ inventory_hostname }}"
    content: "{{ inventory_hostname }} ALL=(ALL) NOPASSWD:ALL"
