- name: ensure /etc/nginx dir exists
  file:
    path: /etc/nginx
    state: directory

- name: copy over docker-compose file
  copy:
    src: docker-compose.yaml
    dest: /etc/nginx/docker-compose.yaml
  notify: restart nginx container

- name: copy over conf file
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx container

- name: deploy nginx container
  docker_compose:
    project_src: /etc/nginx
    state: present